server:
  port: 8016
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: always

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/wanted
    username: root
    password: preonboarding
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create  # TODO: change to `update` later
    properties:
      hibernate:
        auto_quote_keyword: true
        globally_quoted_identifiers: true
        format_sql: true
        show_sql: true

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
